// GENERATED BY generate_ros2_schemas.py
#pragma once
#include <string_view>

namespace ros2schemas {

struct SchemaInfo {
    std::string_view id;
    std::string_view schema;
};

static constexpr SchemaInfo sensor_msgs_msg_Image
    = { .id = "sensor_msgs/msg/Image", .schema = R"(
std_msgs/msg/Header header
uint32 height
uint32 width
string encoding
uint8 is_bigendian
uint32 step
uint8[] data
================================================================================
MSG: std_msgs/msg/Header
builtin_interfaces/msg/Time stamp
string frame_id
================================================================================
MSG: builtin_interfaces/msg/Time
int32 sec
uint32 nanosec
)" };

static constexpr SchemaInfo sensor_msgs_msg_CameraInfo
    = { .id = "sensor_msgs/msg/CameraInfo", .schema = R"(
std_msgs/msg/Header header
uint32 height
uint32 width
string distortion_model
float64[] d
float64[9] k
float64[9] r
float64[12] p
uint32 binning_x
uint32 binning_y
sensor_msgs/msg/RegionOfInterest roi
================================================================================
MSG: std_msgs/msg/Header
builtin_interfaces/msg/Time stamp
string frame_id
================================================================================
MSG: builtin_interfaces/msg/Time
int32 sec
uint32 nanosec
================================================================================
MSG: sensor_msgs/msg/RegionOfInterest
uint32 x_offset
uint32 y_offset
uint32 height
uint32 width
bool do_rectify
)" };

static constexpr SchemaInfo sensor_msgs_msg_PointCloud2
    = { .id = "sensor_msgs/msg/PointCloud2", .schema = R"(
std_msgs/msg/Header header
uint32 height
uint32 width
sensor_msgs/msg/PointField[] fields
bool is_bigendian
uint32 point_step
uint32 row_step
uint8[] data
bool is_dense
================================================================================
MSG: std_msgs/msg/Header
builtin_interfaces/msg/Time stamp
string frame_id
================================================================================
MSG: builtin_interfaces/msg/Time
int32 sec
uint32 nanosec
================================================================================
MSG: sensor_msgs/msg/PointField
string name
uint32 offset
uint8 datatype
uint32 count
)" };

} // namespace ros2schemas
